// <auto-generated />
using BETGaming.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BETGaming.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230116154610_categoeries")]
    partial class categoeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BETGaming.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sandbox",
                            Url = "https://play-lh.googleusercontent.com/QS31MR9QEDSRV4V8qro8YtwT72OvUJJPpWrgyqDLwNgLcEGDe2D7EJnakRJRIhYWUw"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shooters (FPS and TPS)",
                            Url = "https://www.denofgeek.com/wp-content/uploads/2021/07/Far-Cry-2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Multiplayer online battle arena (MOBA)",
                            Url = "https://i.ytimg.com/vi/lD-nWRWo7NU/maxresdefault.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Role-playing (RPG, ARPG, and More)",
                            Url = "https://www.giantbomb.com/a/uploads/scale_medium/9/97089/2256747-4.png"
                        });
                });

            modelBuilder.Entity("BETGaming.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The first game",
                            ImageURL = "images/3.png",
                            Price = 1.0m,
                            Title = "Game 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "The second game",
                            ImageURL = "images/4.png",
                            Price = 2.0m,
                            Title = "Game 2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "the third game",
                            ImageURL = "images/3.png",
                            Price = 3.0m,
                            Title = "Game 3"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "The fourth game",
                            ImageURL = "images/4.png",
                            Price = 4.0m,
                            Title = "Game 4"
                        });
                });

            modelBuilder.Entity("BETGaming.Shared.Product", b =>
                {
                    b.HasOne("BETGaming.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
